services:
  - type: web
    name: meets-api
    runtime: python
    pythonVersion: "3.9.16"
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn Meets.wsgi:application --workers 2
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Meets.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "meets-api.onrender.com"
      - key: PYTHONPATH
        value: "/opt/render/project/src"